name: "dart_n26"
version: 0.1.2
description: "Unofficial dart client for the N26 api. The purpose of this client is only to retrieve data, not to send payments or change settings."
homepage: "https://github.com/fgehrlicher/dart-n26"
repository: "https://github.com/fgehrlicher/dart-n26"
issue_tracker: "https://github.com/fgehrlicher/dart-n26/issues"

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
  test_coverage: ^0.3.0
