name: dart_n26
description: dart n26 api
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
  test_coverage: ^0.3.0
